version: '3.3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=8034965422:AAFbg85ujwC5u3IjhLvowh1h_kIOcZr7h4M
      - DATABASE_URL=postgresql://admin:secret@db:5432/kniga_db
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kniga_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
